/**
 * SEO Quality Gate — Phase 2: pre-publish validation for Articles.
 *
 * WARN WIDELY, BLOCK NARROWLY (spec principle 4). The BLOCK set is only the
 * unambiguous, deterministic, safe checks:
 *   B1  missing/empty title
 *   B2  title > 60 chars
 *   B3  noindex accidentally enabled on a real article (seo.noIndex === true)
 *   B4  broken INTERNAL link — a body link to /tools/<slug> or
 *       /wellness-hub/<slug> whose target slug does not exist
 * ("Invalid JSON-LD" from the spec's block set is N/A at the document level —
 *  JSON-LD is generated by the frontend and its syntax is enforced by the
 *  validate-jsonld CI gate on every build. The hasFAQ↔visible-FAQ mismatch is
 *  already hard-blocked by the hasFAQ field validate in Articles.ts.)
 *
 * Everything else is a WARNING the editor sees and decides on:
 *   W1  meta description missing or outside the advisory range 120–160
 *       (matches the existing editor counters from P16 — deliberately NOT the
 *       spec's 120–155 so the editor never sees two conflicting ranges;
 *       length is advisory, not a ranking rule)
 *   W2  fewer than 5 internal links in the body
 *   W3  fewer than 2 sources
 *   W4  no medical reviewer assigned (YMYL)
 *   W5  hero image has no alt text (only when the alt is KNOWN to be missing —
 *       unknown ⇒ fail safe, no warning)
 *
 * Pure module — no Payload imports; fully unit-tested in publishGate.test.ts.
 */

export interface GateIssue {
  code: string;
  message: string;
}

export interface GateResult {
  blocks: GateIssue[];
  warns: GateIssue[];
}

export interface GateContext {
  toolSlugs: Set<string>;
  articleSlugs: Set<string>;
  categorySlugs: Set<string>;
  /** Media alt for the hero: string = present, null/'' = missing, undefined = unknown (no warning). */
  heroImageAlt?: string | null;
}

/** Advisory range — MUST stay in sync with the P16 editor counters. */
export const DESC_ADVISORY: readonly [number, number] = [120, 160];
export const TITLE_MAX = 60;
export const MIN_INTERNAL_LINKS = 5;
export const MIN_SOURCES = 2;

/** All markdown `](...)` internal hrefs in every string of the layout tree. */
export function extractInternalLinks(node: unknown, out: string[] = []): string[] {
  if (typeof node === 'string') {
    for (const m of node.matchAll(/\]\(\s*(\/[^)\s]*)\s*\)/g)) out.push(m[1]);
    return out;
  }
  if (Array.isArray(node)) {
    for (const n of node) extractInternalLinks(n, out);
    return out;
  }
  if (node && typeof node === 'object') {
    for (const v of Object.values(node as Record<string, unknown>)) extractInternalLinks(v, out);
  }
  return out;
}

/**
 * Broken = links whose FIRST segment is tools/wellness-hub and whose single
 * slug segment is unknown. Deeper paths, query/fragment variants, and every
 * other internal path are deliberately NOT judged (fail safe — B4 must never
 * false-positive).
 */
export function findBrokenInternalLinks(links: string[], ctx: GateContext): string[] {
  const broken: string[] = [];
  for (const raw of links) {
    const clean = raw.split('#')[0].split('?')[0].replace(/\/$/, '');
    const m = clean.match(/^\/(tools|wellness-hub)\/([a-z0-9-]+)$/);
    if (!m) continue;
    const [, section, slug] = m;
    const known =
      section === 'tools'
        ? ctx.toolSlugs.has(slug)
        : ctx.articleSlugs.has(slug) || ctx.categorySlugs.has(slug);
    if (!known) broken.push(clean);
  }
  return [...new Set(broken)];
}

/** Minimal article shape the gate reads — keep loose to survive schema drift. */
export interface GateDoc {
  title?: unknown;
  layout?: unknown;
  seo?: { noIndex?: unknown; metaDescription?: unknown } | null;
  sources?: unknown[] | null;
  reviewer?: unknown;
}

export function runPublishGate(doc: GateDoc, ctx: GateContext): GateResult {
  const blocks: GateIssue[] = [];
  const warns: GateIssue[] = [];

  // ── BLOCKS ──────────────────────────────────────────────────────────────
  const title = typeof doc.title === 'string' ? doc.title.trim() : '';
  if (!title) blocks.push({ code: 'B1', message: 'Missing or empty title.' });
  else if (title.length > TITLE_MAX)
    blocks.push({ code: 'B2', message: `Title is ${title.length} chars (max ${TITLE_MAX}).` });

  if (doc.seo?.noIndex === true)
    blocks.push({ code: 'B3', message: 'noindex is enabled — this article would be invisible to search engines. Untick "No-index" (or keep it a draft).' });

  const links = extractInternalLinks(doc.layout ?? null);
  for (const b of findBrokenInternalLinks(links, ctx))
    blocks.push({ code: 'B4', message: `Broken internal link: ${b} (target does not exist).` });

  // ── WARNINGS ────────────────────────────────────────────────────────────
  const desc = typeof doc.seo?.metaDescription === 'string' ? doc.seo.metaDescription.trim() : '';
  if (!desc) warns.push({ code: 'W1', message: 'No meta description — search engines will improvise one.' });
  else if (desc.length < DESC_ADVISORY[0] || desc.length > DESC_ADVISORY[1])
    warns.push({ code: 'W1', message: `Meta description is ${desc.length} chars (advisory ${DESC_ADVISORY[0]}–${DESC_ADVISORY[1]} — guidance, not a rule).` });

  if (links.length < MIN_INTERNAL_LINKS)
    warns.push({ code: 'W2', message: `Only ${links.length} internal link(s) in the body (aim ≥${MIN_INTERNAL_LINKS} contextual links).` });

  const sources = Array.isArray(doc.sources) ? doc.sources.length : 0;
  if (sources < MIN_SOURCES)
    warns.push({ code: 'W3', message: `${sources} source(s) cited (YMYL content should cite ≥${MIN_SOURCES} reputable references).` });

  if (doc.reviewer == null)
    warns.push({ code: 'W4', message: 'No medical reviewer assigned — YMYL trust signal missing.' });

  if (ctx.heroImageAlt !== undefined && !String(ctx.heroImageAlt ?? '').trim())
    warns.push({ code: 'W5', message: 'Hero image has no alt text.' });

  return { blocks, warns };
}
