/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    tags: Tag;
    authors: Author;
    tools: Tool;
    articles: Article;
    pages: Page;
    redirects: Redirect;
    'tool-usage': ToolUsage;
    personas: Persona;
    profiles: Profile;
    'indexing-status': IndexingStatus;
    'pseo-templates': PseoTemplate;
    'pseo-datasets': PseoDataset;
    'pseo-pages': PseoPage;
    leads: Lead;
    subscribers: Subscriber;
    'push-subscriptions': PushSubscription;
    'push-history': PushHistory;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'tool-usage': ToolUsageSelect<false> | ToolUsageSelect<true>;
    personas: PersonasSelect<false> | PersonasSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    'indexing-status': IndexingStatusSelect<false> | IndexingStatusSelect<true>;
    'pseo-templates': PseoTemplatesSelect<false> | PseoTemplatesSelect<true>;
    'pseo-datasets': PseoDatasetsSelect<false> | PseoDatasetsSelect<true>;
    'pseo-pages': PseoPagesSelect<false> | PseoPagesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    'push-history': PushHistorySelect<false> | PushHistorySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    indexing: Indexing;
    'social-media': SocialMedia;
    'ad-management': AdManagement;
    'lead-gen': LeadGen;
    audience: Audience;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    indexing: IndexingSelect<false> | IndexingSelect<true>;
    'social-media': SocialMediaSelect<false> | SocialMediaSelect<true>;
    'ad-management': AdManagementSelect<false> | AdManagementSelect<true>;
    'lead-gen': LeadGenSelect<false> | LeadGenSelect<true>;
    audience: AudienceSelect<false> | AudienceSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins manage settings, users and redirects. Editors manage content only.
   */
  role: 'admin' | 'editor';
  /**
   * Optional short bio.
   */
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
  /**
   * Allow n8n and other services to authenticate via API key.
   */
  enableAPIKey?: boolean | null;
  /**
   * Auto-generated on save. Copy it now — you will not see it again.
   */
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  /**
   * Optional photographer/source credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Lowercase URL segment. Auto-generated from the name — edit if you need a custom URL.
   */
  slug?: string | null;
  kind?: ('tool' | 'section') | null;
  description?: string | null;
  /**
   * Icon key (e.g. "leaf", "heart-pulse").
   */
  icon?: string | null;
  /**
   * Hex accent, e.g. #16a34a.
   */
  accentColor?: string | null;
  /**
   * CSS variable or hex for dynamic theming (e.g. var(--c-nutrition)). Falls back to accentColor.
   */
  accent?: string | null;
  /**
   * Sort order in nav and grids.
   */
  order?: number | null;
  /**
   * Search-engine and social-share metadata. Derived from content when left blank.
   */
  seo?: {
    /**
     * Title tag — ≤ 60 chars. Front-load your target keyword.
     */
    metaTitle?: string | null;
    /**
     * Override the canonical URL (leave blank to auto-derive).
     */
    canonical?: string | null;
    /**
     * Meta description — 150–155 chars. Include keyword + value proposition + CTA.
     */
    metaDescription?: string | null;
    /**
     * Primary keyword(s) this page targets.
     */
    keywords?: string[] | null;
    /**
     * Check to add <meta name="robots" content="noindex">.
     */
    noIndex?: boolean | null;
    /**
     * Social share image (defaults to site fallback OG image).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override og:title (defaults to metaTitle or page title).
     */
    ogTitle?: string | null;
    /**
     * Override og:description (defaults to metaDescription).
     */
    ogDescription?: string | null;
    /**
     * Override twitter:title (defaults to og:title).
     */
    twitterTitle?: string | null;
    /**
     * Override twitter:description (defaults to og:description).
     */
    twitterDescription?: string | null;
    /**
     * Override twitter:image (defaults to og:image).
     */
    twitterImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Lowercase URL segment. Auto-generated from the name — edit if you need a custom URL.
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Lowercase URL segment. Auto-generated from the name — edit if you need a custom URL.
   */
  slug?: string | null;
  /**
   * e.g. "Research & Writing" or "Medical Review Board".
   */
  role?: string | null;
  /**
   * e.g. "RD, MSc Nutrition" or "Medical reviewer".
   */
  credential?: string | null;
  /**
   * Short professional bio shown on articles.
   */
  bio?: string | null;
  /**
   * 1-2 character monogram for avatar fallback (e.g. "HE", "MR").
   */
  initials?: string | null;
  /**
   * Hex background color for the avatar fallback, e.g. #16a34a.
   */
  color?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Schema.org type for structured data.
   */
  schemaType?: ('Organization' | 'Person') | null;
  links?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and edit calculators with no code. Formula tools use safe math expressions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  name: string;
  category: number | Category;
  toolType: 'formula' | 'coded';
  /**
   * Registered component key (e.g. "BreathingTimer", "MealGenerator").
   */
  codedComponent?: string | null;
  /**
   * Lucide icon for the gradient tile.
   */
  icon?:
    | (
        | 'flame'
        | 'pie-chart'
        | 'egg'
        | 'wheat'
        | 'droplet'
        | 'scale'
        | 'percent'
        | 'target'
        | 'dumbbell'
        | 'ruler'
        | 'person-standing'
        | 'trending-down'
        | 'trending-up'
        | 'weight'
        | 'calendar-clock'
        | 'calendar-days'
        | 'calendar-heart'
        | 'baby'
        | 'heart'
        | 'heart-pulse'
        | 'activity'
        | 'gauge'
        | 'moon'
        | 'moon-star'
        | 'bed'
        | 'alarm-clock'
        | 'clock'
        | 'coffee'
        | 'wine'
        | 'beer'
        | 'hourglass'
        | 'utensils'
        | 'beef'
        | 'cookie'
        | 'footprints'
        | 'timer'
        | 'wind'
        | 'armchair'
        | 'cigarette'
        | 'battery-low'
        | 'flask'
      )
    | null;
  /**
   * Gradient tile color family.
   */
  gradient?:
    | ('orange' | 'amber' | 'cyan' | 'blue' | 'purple' | 'indigo' | 'red' | 'pink' | 'green' | 'teal' | 'brown' | 'sky')
    | null;
  /**
   * Hex, e.g. #16a34a.
   */
  accentColor?: string | null;
  /**
   * e.g. "Under 1 min".
   */
  minutesBadge?: string | null;
  /**
   * On = live. Off = "Coming soon" (hidden from the public site).
   */
  enabled?: boolean | null;
  /**
   * Feature on the homepage / hubs.
   */
  featured?: boolean | null;
  inputs?:
    | {
        label: string;
        /**
         * Variable name used in formulas (letters/numbers, no spaces).
         */
        key: string;
        type?: ('number' | 'select' | 'radio' | 'toggle') | null;
        required?: boolean | null;
        /**
         * Optional metric/imperial unit pair (number inputs).
         */
        unit?: {
          /**
           * e.g. kg, cm
           */
          metricLabel?: string | null;
          /**
           * e.g. lb, in
           */
          imperialLabel?: string | null;
        };
        min?: number | null;
        max?: number | null;
        step?: number | null;
        defaultValue?: number | null;
        /**
         * Helper text shown under the field.
         */
        help?: string | null;
        options?:
          | {
              label?: string | null;
              /**
               * Numeric value used in formulas.
               */
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Each output is a safe math expression (e.g. weight / (height/100)^2). Use a ? b : c for conditions; later outputs can reference earlier output keys.
   */
  outputs?:
    | {
        /**
         * Output variable name.
         */
        key: string;
        label: string;
        /**
         * Safe math over the input variables. No JavaScript — arithmetic & math functions only.
         */
        expression: string;
        /**
         * e.g. kg, %, bpm
         */
        unit?: string | null;
        decimals?: number | null;
        /**
         * Optional ranges → category badge + coloured gauge.
         */
        bands?:
          | {
              /**
               * Inclusive upper bound.
               */
              upTo: number;
              label: string;
              /**
               * Hex.
               */
              color: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  whatItIs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  howCalculated?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  howToRead?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Emits FAQPage structured data automatically.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  sources?:
    | {
        title: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 3–4 related tools to cross-link.
   */
  related?: (number | Tool)[] | null;
  /**
   * Search-engine and social-share metadata. Derived from content when left blank.
   */
  seo?: {
    /**
     * Title tag — ≤ 60 chars. Front-load your target keyword.
     */
    metaTitle?: string | null;
    /**
     * Override the canonical URL (leave blank to auto-derive).
     */
    canonical?: string | null;
    /**
     * Meta description — 150–155 chars. Include keyword + value proposition + CTA.
     */
    metaDescription?: string | null;
    /**
     * Primary keyword(s) this page targets.
     */
    keywords?: string[] | null;
    /**
     * Check to add <meta name="robots" content="noindex">.
     */
    noIndex?: boolean | null;
    /**
     * Social share image (defaults to site fallback OG image).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override og:title (defaults to metaTitle or page title).
     */
    ogTitle?: string | null;
    /**
     * Override og:description (defaults to metaDescription).
     */
    ogDescription?: string | null;
    /**
     * Override twitter:title (defaults to og:title).
     */
    twitterTitle?: string | null;
    /**
     * Override twitter:description (defaults to og:description).
     */
    twitterDescription?: string | null;
    /**
     * Override twitter:image (defaults to og:image).
     */
    twitterImage?: (number | null) | Media;
  };
  /**
   * Lowercase URL segment. Auto-generated from the name — edit if you need a custom URL.
   */
  slug?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Short summary for cards and the article lead.
   */
  excerpt?: string | null;
  /**
   * Featured image.
   */
  heroImage?: (number | null) | Media;
  /**
   * Build the page with modular blocks.
   */
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            cta: {
              label: string;
              url: string;
            };
            /**
             * Full-width background image behind the hero.
             */
            backgroundImage?: (number | null) | Media;
            overlay?: ('dark' | 'light' | 'none') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Select which calculator to embed inline.
             */
            tool: number | Tool;
            variant?: ('inline' | 'banner') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calculatorEmbed';
          }
        | {
            /**
             * Image (left column).
             */
            image?: (number | null) | Media;
            imageSide?: ('left' | 'right') | null;
            heading?: string | null;
            /**
             * Body text for the text column.
             */
            text: string;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumn';
          }
        | {
            /**
             * The bold hook line (e.g. "Did you know?").
             */
            hook: string;
            /**
             * Supporting sentence beneath the hook.
             */
            subtext?: string | null;
            /**
             * Background hex color.
             */
            bgColor?: string | null;
            /**
             * Text hex color.
             */
            textColor?: string | null;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'viralHookBanner';
          }
        | {
            /**
             * Select the calculator or tool to embed inline.
             */
            tool: number | Tool;
            /**
             * Optional CTA label shown with the embed (e.g. "Try it: Calorie Calculator").
             */
            label?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'toolEmbed';
          }
        | {
            /**
             * Optional heading above the FAQ block (e.g. "People also ask").
             */
            heading?: string | null;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'peopleAlsoAsk';
          }
        | {
            style?: ('p' | 'h2' | 'h3') | null;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            style?: ('unordered' | 'ordered') | null;
            items: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            tone?: ('info' | 'tip' | 'warning') | null;
            title?: string | null;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            caption?: string | null;
            headers?: string[] | null;
            rows?:
              | {
                  cells?: string[] | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
      )[]
    | null;
  /**
   * People-also-ask questions. Emits FAQPage structured data.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 2–3 reputable references.
   */
  sources?:
    | {
        label: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 2–3 tools to cross-link.
   */
  relatedTools?: (number | Tool)[] | null;
  /**
   * Search-engine and social-share metadata. Derived from content when left blank.
   */
  seo?: {
    /**
     * Title tag — ≤ 60 chars. Front-load your target keyword.
     */
    metaTitle?: string | null;
    /**
     * Override the canonical URL (leave blank to auto-derive).
     */
    canonical?: string | null;
    /**
     * Meta description — 150–155 chars. Include keyword + value proposition + CTA.
     */
    metaDescription?: string | null;
    /**
     * Primary keyword(s) this page targets.
     */
    keywords?: string[] | null;
    /**
     * Check to add <meta name="robots" content="noindex">.
     */
    noIndex?: boolean | null;
    /**
     * Social share image (defaults to site fallback OG image).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override og:title (defaults to metaTitle or page title).
     */
    ogTitle?: string | null;
    /**
     * Override og:description (defaults to metaDescription).
     */
    ogDescription?: string | null;
    /**
     * Override twitter:title (defaults to og:title).
     */
    twitterTitle?: string | null;
    /**
     * Override twitter:description (defaults to og:description).
     */
    twitterDescription?: string | null;
    /**
     * Override twitter:image (defaults to og:image).
     */
    twitterImage?: (number | null) | Media;
  };
  /**
   * Lowercase URL segment. Auto-generated from the name — edit if you need a custom URL.
   */
  slug?: string | null;
  category?: (number | null) | Category;
  /**
   * Written by.
   */
  author?: (number | null) | Author;
  /**
   * Medically reviewed by.
   */
  reviewer?: (number | null) | Author;
  tags?: (number | Tag)[] | null;
  /**
   * Used for ordering and scheduling.
   */
  publishDate?: string | null;
  /**
   * Last substantive update for YMYL freshness signals.
   */
  updatedDate?: string | null;
  /**
   * Show as the featured/hero article on the Wellness Hub.
   */
  featured?: boolean | null;
  /**
   * The primary tool to embed inline within the article.
   */
  primaryTool?: (number | null) | Tool;
  /**
   * Explicitly link related articles (auto-fallback to same-category when empty).
   */
  relatedArticles?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Page-level hero image.
   */
  heroImage?: (number | null) | Media;
  /**
   * Build the page with modular blocks.
   */
  layout: (
    | {
        title: string;
        subtitle?: string | null;
        cta: {
          label: string;
          url: string;
        };
        /**
         * Full-width background image behind the hero.
         */
        backgroundImage?: (number | null) | Media;
        overlay?: ('dark' | 'light' | 'none') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Select which calculator to embed inline.
         */
        tool: number | Tool;
        variant?: ('inline' | 'banner') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'calculatorEmbed';
      }
    | {
        /**
         * Image (left column).
         */
        image?: (number | null) | Media;
        imageSide?: ('left' | 'right') | null;
        heading?: string | null;
        /**
         * Body text for the text column.
         */
        text: string;
        cta?: {
          label?: string | null;
          url?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'twoColumn';
      }
    | {
        /**
         * The bold hook line (e.g. "Did you know?").
         */
        hook: string;
        /**
         * Supporting sentence beneath the hook.
         */
        subtext?: string | null;
        /**
         * Background hex color.
         */
        bgColor?: string | null;
        /**
         * Text hex color.
         */
        textColor?: string | null;
        cta?: {
          label?: string | null;
          url?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'viralHookBanner';
      }
    | {
        /**
         * Select the calculator or tool to embed inline.
         */
        tool: number | Tool;
        /**
         * Optional CTA label shown with the embed (e.g. "Try it: Calorie Calculator").
         */
        label?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'toolEmbed';
      }
    | {
        /**
         * Optional heading above the FAQ block (e.g. "People also ask").
         */
        heading?: string | null;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'peopleAlsoAsk';
      }
    | {
        style?: ('p' | 'h2' | 'h3') | null;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'text';
      }
    | {
        style?: ('unordered' | 'ordered') | null;
        items: {
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'list';
      }
    | {
        tone?: ('info' | 'tip' | 'warning') | null;
        title?: string | null;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'callout';
      }
    | {
        caption?: string | null;
        headers?: string[] | null;
        rows?:
          | {
              cells?: string[] | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'table';
      }
  )[];
  /**
   * Search-engine and social-share metadata. Derived from content when left blank.
   */
  seo?: {
    /**
     * Title tag — ≤ 60 chars. Front-load your target keyword.
     */
    metaTitle?: string | null;
    /**
     * Override the canonical URL (leave blank to auto-derive).
     */
    canonical?: string | null;
    /**
     * Meta description — 150–155 chars. Include keyword + value proposition + CTA.
     */
    metaDescription?: string | null;
    /**
     * Primary keyword(s) this page targets.
     */
    keywords?: string[] | null;
    /**
     * Check to add <meta name="robots" content="noindex">.
     */
    noIndex?: boolean | null;
    /**
     * Social share image (defaults to site fallback OG image).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override og:title (defaults to metaTitle or page title).
     */
    ogTitle?: string | null;
    /**
     * Override og:description (defaults to metaDescription).
     */
    ogDescription?: string | null;
    /**
     * Override twitter:title (defaults to og:title).
     */
    twitterTitle?: string | null;
    /**
     * Override twitter:description (defaults to og:description).
     */
    twitterDescription?: string | null;
    /**
     * Override twitter:image (defaults to og:image).
     */
    twitterImage?: (number | null) | Media;
  };
  /**
   * Lowercase URL segment. Auto-generated from the name — edit if you need a custom URL.
   */
  slug?: string | null;
  /**
   * Used for ordering and scheduling.
   */
  publishDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Old path, e.g. /old-bmi
   */
  from: string;
  /**
   * New path or URL, e.g. /tools/bmi-calculator
   */
  to: string;
  type?: ('301' | '302') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anonymous per-session usage data for calculator tools.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-usage".
 */
export interface ToolUsage {
  id: number;
  tool: number | Tool;
  sessionId: string;
  /**
   * Anonymous profile (if linked).
   */
  profile?: (number | null) | Profile;
  startedAt: string;
  completedAt?: string | null;
  /**
   * Key of the last input field the user interacted with before leaving.
   */
  lastFieldReached?: string | null;
  /**
   * Number of inputs the user filled before leaving.
   */
  totalFieldsCompleted?: number | null;
  /**
   * Total input fields on this tool.
   */
  totalFields?: number | null;
  completed?: boolean | null;
  /**
   * Session duration in seconds.
   */
  duration?: number | null;
  referrer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anonymous public user profiles. Personas are auto-assigned by usage patterns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  /**
   * UUID generated client-side, stored in localStorage.
   */
  profileId: string;
  /**
   * Auto-assigned personas based on tool usage.
   */
  personas?: (number | Persona)[] | null;
  /**
   * Total number of tool interactions.
   */
  toolUsageCount?: number | null;
  /**
   * Last tool interaction timestamp.
   */
  lastActiveAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User personas assigned automatically based on tool usage patterns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas".
 */
export interface Persona {
  id: number;
  /**
   * e.g. "Bodybuilder", "Weight Loss Seeker"
   */
  name: string;
  description?: string | null;
  /**
   * Lucide icon name, e.g. "dumbbell", "flame".
   */
  icon?: string | null;
  /**
   * Hex, e.g. #ef4444.
   */
  color?: string | null;
  /**
   * Off = persona is not assigned to any profile.
   */
  enabled?: boolean | null;
  /**
   * Each rule is a condition the profile must satisfy.
   */
  rules?:
    | {
        matchType: 'tool' | 'category';
        tool?: (number | null) | Tool;
        category?: (number | null) | Category;
        /**
         * Times user must use this tool/category.
         */
        minUsage?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lowercase URL segment. Auto-generated from the name — edit if you need a custom URL.
   */
  slug?: string | null;
  /**
   * Auto-updated count of profiles assigned this persona.
   */
  profilesCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * History of IndexNow and Google Indexing API pings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indexing-status".
 */
export interface IndexingStatus {
  id: number;
  /**
   * Collection slug (tools, articles, pages).
   */
  docType: string;
  docSlug: string;
  url: string;
  engine:
    | 'https://api.indexnow.org/indexnow'
    | 'https://www.bing.com/indexnow'
    | 'https://search.yandex.com/indexnow'
    | 'google';
  status: 'pending' | 'success' | 'failed';
  httpStatus?: number | null;
  error?: string | null;
  submittedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Page templates for programmatic SEO pages. Use {{variable}} placeholders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pseo-templates".
 */
export interface PseoTemplate {
  id: number;
  name: string;
  /**
   * Used as prefix for generated page slugs.
   */
  slug: string;
  status?: ('draft' | 'published') | null;
  /**
   * H1 template — e.g. "{{keyword}} Calculator for {{audience}}"
   */
  headlineTemplate: string;
  /**
   * H2 subtitle template.
   */
  subheadlineTemplate?: string | null;
  /**
   * Main body HTML. Supports {{variable}} placeholders. Use standard HTML.
   */
  bodyTemplate: string;
  /**
   * Call-to-action text template — e.g. "Try the {{keyword}} Calculator Now"
   */
  ctaTemplate?: string | null;
  /**
   * Where the CTA goes. Use {{slug}} to link to the target calculator.
   */
  ctaLink?: string | null;
  /**
   * Meta title — e.g. "{{keyword}} Calculator: Free {{audience}} Tool ({{year}})"
   */
  metaTitleTemplate: string;
  /**
   * Meta description — e.g. "Use our free {{keyword}} calculator for {{audience}}. Check your {{healthGoal}} in minutes."
   */
  metaDescTemplate: string;
  /**
   * H1 override for the rendered page. Falls back to headlineTemplate.
   */
  h1Template?: string | null;
  /**
   * Slug pattern — e.g. "{{keyword}}-calculator-{{audience}}". Auto-slugified.
   */
  slugTemplate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * CSV datasets containing keyword/variable rows. Each row generates one pSEO page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pseo-datasets".
 */
export interface PseoDataset {
  id: number;
  name: string;
  template: number | PseoTemplate;
  status?: ('draft' | 'ready' | 'generated') | null;
  /**
   * CSV file with header row. Columns become {{variables}} in templates.
   */
  csvFile: number | Media;
  /**
   * Detected CSV columns + config (auto-populated on upload).
   */
  columns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Number of data rows in the CSV.
   */
  rowCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Generated programmatic SEO pages. One per CSV row.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pseo-pages".
 */
export interface PseoPage {
  id: number;
  slug: string;
  status?: ('draft' | 'published') | null;
  template: number | PseoTemplate;
  dataset: number | PseoDataset;
  /**
   * Primary keyword from the CSV row.
   */
  keyword?: string | null;
  /**
   * All column values from the CSV row stored as key-value pairs.
   */
  variables?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  headline?: string | null;
  subheadline?: string | null;
  /**
   * Rendered page body HTML.
   */
  bodyHtml?: string | null;
  ctaText?: string | null;
  ctaUrl?: string | null;
  /**
   * Rendered SEO metadata.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Lead-capture submissions from calculator result CTAs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  email: string;
  /**
   * First name (if collected).
   */
  name?: string | null;
  /**
   * Which offer they responded to (offer name from LeadGen).
   */
  offer?: string | null;
  /**
   * Which tool/page they were on when submitting.
   */
  tool?: string | null;
  /**
   * Full URL of the page where the form was submitted.
   */
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email subscribers captured via lead forms, CSV imports, or n8n sync.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * First name or full name.
   */
  name?: string | null;
  /**
   * Content categories this subscriber is interested in.
   */
  interests?:
    | (
        | 'weight-loss'
        | 'nutrition'
        | 'fitness'
        | 'sleep'
        | 'heart-health'
        | 'mental-wellness'
        | 'womens-health'
        | 'general'
      )[]
    | null;
  source?: ('web-form' | 'csv-import' | 'n8n-sync' | 'api') | null;
  subscribedAt?: string | null;
  /**
   * Set when the subscriber opts out.
   */
  unsubscribedAt?: string | null;
  /**
   * Flexible extra data (tool used, source page, etc.).
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Browser push notification subscriptions (VAPID web push).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: number;
  /**
   * Push endpoint URL from the browser.
   */
  endpoint: string;
  /**
   * Auth secret from the browser subscription.
   */
  authKey: string;
  /**
   * P256DH public key from the browser subscription.
   */
  p256dhKey: string;
  /**
   * Browser user-agent string.
   */
  userAgent?: string | null;
  subscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit log of all push notifications sent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-history".
 */
export interface PushHistory {
  id: number;
  /**
   * Push notification title.
   */
  title: string;
  /**
   * Push notification body text.
   */
  body?: string | null;
  /**
   * Article this push relates to (optional).
   */
  article?: (number | null) | Article;
  /**
   * URL opened when the notification is clicked.
   */
  url?: string | null;
  sentCount?: number | null;
  failedCount?: number | null;
  /**
   * Detailed error log for failed sends.
   */
  errors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'tool-usage';
        value: number | ToolUsage;
      } | null)
    | ({
        relationTo: 'personas';
        value: number | Persona;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'indexing-status';
        value: number | IndexingStatus;
      } | null)
    | ({
        relationTo: 'pseo-templates';
        value: number | PseoTemplate;
      } | null)
    | ({
        relationTo: 'pseo-datasets';
        value: number | PseoDataset;
      } | null)
    | ({
        relationTo: 'pseo-pages';
        value: number | PseoPage;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: number | PushSubscription;
      } | null)
    | ({
        relationTo: 'push-history';
        value: number | PushHistory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  description?: T;
  icon?: T;
  accentColor?: T;
  accent?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        canonical?: T;
        metaDescription?: T;
        keywords?: T;
        noIndex?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  credential?: T;
  bio?: T;
  initials?: T;
  color?: T;
  avatar?: T;
  schemaType?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  toolType?: T;
  codedComponent?: T;
  icon?: T;
  gradient?: T;
  accentColor?: T;
  minutesBadge?: T;
  enabled?: T;
  featured?: T;
  inputs?:
    | T
    | {
        label?: T;
        key?: T;
        type?: T;
        required?: T;
        unit?:
          | T
          | {
              metricLabel?: T;
              imperialLabel?: T;
            };
        min?: T;
        max?: T;
        step?: T;
        defaultValue?: T;
        help?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  outputs?:
    | T
    | {
        key?: T;
        label?: T;
        expression?: T;
        unit?: T;
        decimals?: T;
        bands?:
          | T
          | {
              upTo?: T;
              label?: T;
              color?: T;
              id?: T;
            };
        id?: T;
      };
  whatItIs?: T;
  howCalculated?: T;
  howToRead?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  related?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        canonical?: T;
        metaDescription?: T;
        keywords?: T;
        noIndex?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
      };
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundImage?: T;
              overlay?: T;
              id?: T;
              blockName?: T;
            };
        calculatorEmbed?:
          | T
          | {
              tool?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        twoColumn?:
          | T
          | {
              image?: T;
              imageSide?: T;
              heading?: T;
              text?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        viralHookBanner?:
          | T
          | {
              hook?: T;
              subtext?: T;
              bgColor?: T;
              textColor?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        toolEmbed?:
          | T
          | {
              tool?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
        peopleAlsoAsk?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              style?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              style?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              tone?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              caption?: T;
              headers?: T;
              rows?:
                | T
                | {
                    cells?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  relatedTools?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        canonical?: T;
        metaDescription?: T;
        keywords?: T;
        noIndex?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
      };
  slug?: T;
  category?: T;
  author?: T;
  reviewer?: T;
  tags?: T;
  publishDate?: T;
  updatedDate?: T;
  featured?: T;
  primaryTool?: T;
  relatedArticles?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundImage?: T;
              overlay?: T;
              id?: T;
              blockName?: T;
            };
        calculatorEmbed?:
          | T
          | {
              tool?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        twoColumn?:
          | T
          | {
              image?: T;
              imageSide?: T;
              heading?: T;
              text?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        viralHookBanner?:
          | T
          | {
              hook?: T;
              subtext?: T;
              bgColor?: T;
              textColor?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        toolEmbed?:
          | T
          | {
              tool?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
        peopleAlsoAsk?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              style?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              style?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              tone?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              caption?: T;
              headers?: T;
              rows?:
                | T
                | {
                    cells?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        canonical?: T;
        metaDescription?: T;
        keywords?: T;
        noIndex?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
      };
  slug?: T;
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-usage_select".
 */
export interface ToolUsageSelect<T extends boolean = true> {
  tool?: T;
  sessionId?: T;
  profile?: T;
  startedAt?: T;
  completedAt?: T;
  lastFieldReached?: T;
  totalFieldsCompleted?: T;
  totalFields?: T;
  completed?: T;
  duration?: T;
  referrer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas_select".
 */
export interface PersonasSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  color?: T;
  enabled?: T;
  rules?:
    | T
    | {
        matchType?: T;
        tool?: T;
        category?: T;
        minUsage?: T;
        id?: T;
      };
  slug?: T;
  profilesCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  profileId?: T;
  personas?: T;
  toolUsageCount?: T;
  lastActiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indexing-status_select".
 */
export interface IndexingStatusSelect<T extends boolean = true> {
  docType?: T;
  docSlug?: T;
  url?: T;
  engine?: T;
  status?: T;
  httpStatus?: T;
  error?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pseo-templates_select".
 */
export interface PseoTemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  headlineTemplate?: T;
  subheadlineTemplate?: T;
  bodyTemplate?: T;
  ctaTemplate?: T;
  ctaLink?: T;
  metaTitleTemplate?: T;
  metaDescTemplate?: T;
  h1Template?: T;
  slugTemplate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pseo-datasets_select".
 */
export interface PseoDatasetsSelect<T extends boolean = true> {
  name?: T;
  template?: T;
  status?: T;
  csvFile?: T;
  columns?: T;
  rowCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pseo-pages_select".
 */
export interface PseoPagesSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  template?: T;
  dataset?: T;
  keyword?: T;
  variables?: T;
  headline?: T;
  subheadline?: T;
  bodyHtml?: T;
  ctaText?: T;
  ctaUrl?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  offer?: T;
  tool?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  interests?: T;
  source?: T;
  subscribedAt?: T;
  unsubscribedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  endpoint?: T;
  authKey?: T;
  p256dhKey?: T;
  userAgent?: T;
  subscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-history_select".
 */
export interface PushHistorySelect<T extends boolean = true> {
  title?: T;
  body?: T;
  article?: T;
  url?: T;
  sentCount?: T;
  failedCount?: T;
  errors?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteTitle: string;
  tagline?: string | null;
  description?: string | null;
  /**
   * Site logo (SVG preferred).
   */
  logo?: (number | null) | Media;
  /**
   * Favicon — 32×32 PNG or ICO.
   */
  favicon?: (number | null) | Media;
  /**
   * Brand primary (e.g. button backgrounds).
   */
  primaryColor?: string | null;
  /**
   * Brand secondary (e.g. accent links).
   */
  secondaryColor?: string | null;
  /**
   * Fallback OG image for social shares.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Public contact email (e.g. hello@healthylifestyles.com).
   */
  contactEmail?: string | null;
  /**
   * Drag to reorder. Appears in the header.
   */
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform?:
          | (
              | 'Facebook'
              | 'X (Twitter)'
              | 'Instagram'
              | 'YouTube'
              | 'LinkedIn'
              | 'Pinterest'
              | 'TikTok'
              | 'Threads'
              | 'Bluesky'
            )
          | null;
        url: string;
        /**
         * Brand hex color for this platform (e.g. #1877F2 for Facebook).
         */
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. G-XXXXXXXXXX
   */
  ga4Id?: string | null;
  /**
   * Verification token.
   */
  searchConsoleId?: string | null;
  /**
   * Master toggle for ad slots.
   */
  adsEnabled?: boolean | null;
  /**
   * ca-pub-…
   */
  adsenseClient?: string | null;
  affiliateDisclosure?: string | null;
  cookieConsentText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indexing".
 */
export interface Indexing {
  id: number;
  /**
   * IndexNow key (a UUID). Create a file named <key>.txt at your site root.
   */
  indexNowKey?: string | null;
  /**
   * Google service-account JSON (paste the full key). Enables Google Indexing API.
   */
  googleServiceAccount?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media".
 */
export interface SocialMedia {
  id: number;
  profiles?:
    | {
        platform:
          | 'Facebook'
          | 'X (Twitter)'
          | 'Instagram'
          | 'YouTube'
          | 'LinkedIn'
          | 'Pinterest'
          | 'TikTok'
          | 'Threads'
          | 'Bluesky';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * twitter:site — e.g. @HealthyLifeStyl
   */
  twitterSite?: string | null;
  /**
   * fb:app_id
   */
  facebookAppId?: string | null;
  /**
   * Google Search publisher link (sameAs).
   */
  publisherUrl?: string | null;
  defaultShareText?: string | null;
  /**
   * Fallback OG image (1200×630px) when a document has none.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Fallback X/Twitter card image (1200×600px) when a document has none.
   */
  defaultTwitterImage?: (number | null) | Media;
  twitterCardStyle?: ('summary' | 'summary_large_image') | null;
  /**
   * og:locale
   */
  ogLocale?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-management".
 */
export interface AdManagement {
  id: number;
  /**
   * Master toggle for AdSense. Disable to show only placeholders.
   */
  adsenseEnabled?: boolean | null;
  /**
   * e.g. ca-pub-1234567890123456
   */
  adsenseClient?: string | null;
  /**
   * Load ads via IntersectionObserver (250px viewport margin). Prevents layout shift.
   */
  lazyLoad?: boolean | null;
  /**
   * Run AdSense/Analytics scripts in a web worker so they never block the main thread.
   */
  partytownEnabled?: boolean | null;
  slots?:
    | {
        placement: 'header' | 'sidebar' | 'inContent' | 'stickyFooter' | 'afterResult' | 'midContent';
        enabled?: boolean | null;
        format?: ('auto' | 'rectangle' | 'leaderboard' | 'sidebar' | 'mobileBanner') | null;
        /**
         * Optional admin label.
         */
        label?: string | null;
        /**
         * AdSense data-ad-slot. Only used when AdSense is enabled.
         */
        adsenseSlotId?: string | null;
        /**
         * Custom ad code (HTML/JS). Used instead of AdSense when provided.
         */
        customCode?: string | null;
        /**
         * If set, an affiliate banner replaces AdSense for this slot.
         */
        affiliateBanner?: {
          image?: (number | null) | Media;
          alt?: string | null;
          url?: string | null;
          width?: number | null;
          height?: number | null;
        };
        id?: string | null;
      }[]
    | null;
  affiliates?:
    | {
        name: string;
        enabled?: boolean | null;
        url: string;
        image: number | Media;
        alt?: string | null;
        width?: number | null;
        height?: number | null;
        /**
         * Which slots this banner can appear in (leave empty for all).
         */
        targetSlots?: ('header' | 'sidebar' | 'inContent' | 'stickyFooter' | 'afterResult')[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-gen".
 */
export interface LeadGen {
  id: number;
  /**
   * Master toggle for all lead-gen CTAs.
   */
  enabled?: boolean | null;
  /**
   * Message shown after a successful submission.
   */
  successMessage?: string | null;
  offers?:
    | {
        /**
         * Internal label (not shown to users).
         */
        name: string;
        enabled?: boolean | null;
        /**
         * Big CTA headline, e.g. "Get Your Personalized BMI Report".
         */
        headline: string;
        /**
         * Short explanation of what they get.
         */
        description?: string | null;
        /**
         * What the user receives in exchange for their email.
         */
        offerType?: ('pdf' | 'tips') | null;
        /**
         * The PDF file users will download after submitting.
         */
        pdf?: (number | null) | Media;
        /**
         * Tips content shown after submission (can include personalized placeholders like {{value}}).
         */
        tipsText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Text on the submit button.
         */
        buttonLabel?: string | null;
        /**
         * Show a "First name" field alongside email.
         */
        collectName?: boolean | null;
        /**
         * Which tools show this offer. Leave empty to show on all tools.
         */
        tools?: (number | Tool)[] | null;
        placement?: ('afterResult' | 'sidebar' | 'midContent') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Your n8n webhook URL where leads are forwarded (POST JSON). Leave empty to log locally.
   */
  n8nWebhookUrl?: string | null;
  /**
   * Optional API key sent as Authorization header to the n8n webhook.
   */
  n8nApiKey?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audience".
 */
export interface Audience {
  id: number;
  /**
   * n8n webhook URL for new subscriber events. Leave empty to skip forwarding.
   */
  n8nWebhookUrl?: string | null;
  /**
   * Optional Bearer token sent to the n8n webhook as Authorization header.
   */
  n8nApiKey?: string | null;
  /**
   * When enabled, each new subscriber is POSTed to the n8n webhook.
   */
  forwardOnCreate?: boolean | null;
  /**
   * Master toggle for web push notifications.
   */
  pushEnabled?: boolean | null;
  /**
   * VAPID subject (mailto: or URL), e.g. mailto:hello@healthylifestyles.com
   */
  vapidSubject?: string | null;
  /**
   * VAPID public key. Generate with: npx web-push generate-vapid-keys
   */
  vapidPublicKey?: string | null;
  /**
   * VAPID private key (kept secret, never exposed to the client).
   */
  vapidPrivateKey?: string | null;
  /**
   * Default icon URL for push notifications (120x120px minimum).
   */
  defaultIcon?: string | null;
  /**
   * When an article is published, automatically send a push notification to all subscribers.
   */
  autoPushOnPublish?: boolean | null;
  /**
   * Upload a CSV file with subscriber data. Required columns: email. Optional: name, interests.
   */
  csvFile?: (number | null) | Media;
  /**
   * Column name in the CSV containing email addresses.
   */
  csvEmailColumn?: string | null;
  /**
   * Column name in the CSV containing subscriber names (optional).
   */
  csvNameColumn?: string | null;
  /**
   * Column name in the CSV containing interest tags (semicolon-separated, optional).
   */
  csvInterestsColumn?: string | null;
  /**
   * Status of the last CSV import.
   */
  csvImportStatus?: ('idle' | 'importing' | 'complete' | 'failed') | null;
  /**
   * Result summary from the last CSV import.
   */
  csvImportResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Projected revenue per 1,000 tool sessions (USD). Used only for the "Projected Revenue" card on the dashboard — it is an estimate, not real earnings. Adjust to match your AdSense/monetization RPM.
   */
  projectedRpm?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  favicon?: T;
  primaryColor?: T;
  secondaryColor?: T;
  defaultOgImage?: T;
  contactEmail?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightText?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        color?: T;
        id?: T;
      };
  ga4Id?: T;
  searchConsoleId?: T;
  adsEnabled?: T;
  adsenseClient?: T;
  affiliateDisclosure?: T;
  cookieConsentText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indexing_select".
 */
export interface IndexingSelect<T extends boolean = true> {
  indexNowKey?: T;
  googleServiceAccount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media_select".
 */
export interface SocialMediaSelect<T extends boolean = true> {
  profiles?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  twitterSite?: T;
  facebookAppId?: T;
  publisherUrl?: T;
  defaultShareText?: T;
  defaultOgImage?: T;
  defaultTwitterImage?: T;
  twitterCardStyle?: T;
  ogLocale?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-management_select".
 */
export interface AdManagementSelect<T extends boolean = true> {
  adsenseEnabled?: T;
  adsenseClient?: T;
  lazyLoad?: T;
  partytownEnabled?: T;
  slots?:
    | T
    | {
        placement?: T;
        enabled?: T;
        format?: T;
        label?: T;
        adsenseSlotId?: T;
        customCode?: T;
        affiliateBanner?:
          | T
          | {
              image?: T;
              alt?: T;
              url?: T;
              width?: T;
              height?: T;
            };
        id?: T;
      };
  affiliates?:
    | T
    | {
        name?: T;
        enabled?: T;
        url?: T;
        image?: T;
        alt?: T;
        width?: T;
        height?: T;
        targetSlots?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-gen_select".
 */
export interface LeadGenSelect<T extends boolean = true> {
  enabled?: T;
  successMessage?: T;
  offers?:
    | T
    | {
        name?: T;
        enabled?: T;
        headline?: T;
        description?: T;
        offerType?: T;
        pdf?: T;
        tipsText?: T;
        buttonLabel?: T;
        collectName?: T;
        tools?: T;
        placement?: T;
        id?: T;
      };
  n8nWebhookUrl?: T;
  n8nApiKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audience_select".
 */
export interface AudienceSelect<T extends boolean = true> {
  n8nWebhookUrl?: T;
  n8nApiKey?: T;
  forwardOnCreate?: T;
  pushEnabled?: T;
  vapidSubject?: T;
  vapidPublicKey?: T;
  vapidPrivateKey?: T;
  defaultIcon?: T;
  autoPushOnPublish?: T;
  csvFile?: T;
  csvEmailColumn?: T;
  csvNameColumn?: T;
  csvInterestsColumn?: T;
  csvImportStatus?: T;
  csvImportResult?: T;
  projectedRpm?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'articles';
      value: number | Article;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}