'use client';
import React from 'react';
import { useFormFields } from '@payloadcms/ui';

/**
 * Visible "AI draft — review before publishing" banner. Shows at the top of the
 * Articles edit view whenever the doc is AI-generated and a human hasn't yet
 * ticked `reviewedByHuman`. Reads both flags from live form state.
 */
export const AiDraftBanner: React.FC = () => {
  const [aiGenerated, reviewed] = useFormFields(([fields]) => [
    fields?.aiGenerated?.value,
    fields?.reviewedByHuman?.value,
  ]) as (boolean | undefined)[];

  if (!aiGenerated || reviewed) return null;

  return (
    <div className="hls-aidraft" role="status">
      <span className="hls-aidraft__icon" aria-hidden="true">✨</span>
      <div className="hls-aidraft__body">
        <strong>AI draft — review before publishing.</strong>
        <p>
          This article was generated by AI and has <em>not</em> been human-reviewed. Verify the
          facts, sources, and safety framing, then tick <b>“Reviewed by human”</b> in the sidebar to
          clear this notice.
        </p>
      </div>
    </div>
  );
};

export default AiDraftBanner;
